"""
AI Trading System - Core Data Models

This module defines the core data structures used throughout the AI trading system.
All classes are immutable dataclasses to ensure data consistency and thread safety.
"""

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional, Union

# Re-export ActionType and EvidenceBasedDecision from provider.base for backward compatibility
from src.ai.provider.base import (
    ActionType,
    EvidenceBasedDecision,
    TradeResult as SimpleTradeResult,  # Simple version from provider.base
)


class SignalStrength(str, Enum):
    """Signal strength levels."""

    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"


class MarketRegime(str, Enum):
    """Market regime classifications."""

    TRENDING_UP = "TRENDING_UP"
    TRENDING_DOWN = "TRENDING_DOWN"
    RANGING = "RANGING"
    VOLATILE = "VOLATILE"
    UNKNOWN = "UNKNOWN"


class TradeOutcome(str, Enum):
    """Trade outcome classifications."""

    WIN = "WIN"
    LOSS = "LOSS"
    BREAKEVEN = "BREAKEVEN"
    OPEN = "OPEN"
    CANCELLED = "CANCELLED"


@dataclass(frozen=True)
class TradingSignal:
    """
    A trading signal generated by the AI system.

    This represents the raw output from signal generation components,
    which may be combined with other signals to form a final decision.

    Attributes:
        symbol: Trading pair symbol (e.g., "BTC/USDT")
        timestamp: When the signal was generated
        signal_type: Type of signal (BUY, SELL, PASS)
        strength: Signal strength (STRONG, MODERATE, WEAK)
        evidence_count: Number of evidence points supporting this signal
        source: Component that generated this signal
        evidence_chain: List of evidence descriptions in order of importance
        metadata: Additional signal-specific data
    """

    symbol: str
    timestamp: datetime
    signal_type: ActionType
    strength: SignalStrength
    evidence_count: int
    evidence_chain: List[str]
    source: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate the signal after initialization."""
        if self.evidence_count < 0:
            raise ValueError("evidence_count must be non-negative")
        if self.evidence_count != len(self.evidence_chain):
            raise ValueError("evidence_count must match length of evidence_chain")

    def is_actionable(self) -> bool:
        """Check if this signal is strong enough to act upon."""
        return (
            self.signal_type != ActionType.HOLD
            and self.strength in (SignalStrength.STRONG, SignalStrength.MODERATE)
            and self.evidence_count >= 2
        )


@dataclass(frozen=True)
class MarketContext:
    """
    Market context information for trading decisions.

    This captures the broader market environment to inform
    trading decisions with situational awareness.

    Attributes:
        timestamp: When the context was captured
        regime: Current market regime classification
        volatility_index: Volatility measure (e.g., ATR or VIX)
        trend_strength: Trend strength indicator (0-1)
        support_levels: Key support price levels
        resistance_levels: Key resistance price levels
        volume_profile: Volume distribution data
        correlation_matrix: Cross-asset correlations
        macro_events: Upcoming macroeconomic events
    """

    timestamp: datetime
    regime: MarketRegime
    volatility_index: float
    trend_strength: float
    support_levels: List[float] = field(default_factory=list)
    resistance_levels: List[float] = field(default_factory=list)
    volume_profile: Dict[str, Any] = field(default_factory=dict)
    correlation_matrix: Dict[str, Dict[str, float]] = field(default_factory=dict)
    macro_events: List[Dict[str, Any]] = field(default_factory=list)

    def __post_init__(self):
        """Validate the market context after initialization."""
        if not 0 <= self.trend_strength <= 1:
            raise ValueError("trend_strength must be between 0 and 1")
        if self.volatility_index < 0:
            raise ValueError("volatility_index must be non-negative")

    def is_favorable_for_trading(self) -> bool:
        """Check if market conditions are favorable for trading."""
        return (
            self.regime != MarketRegime.UNKNOWN
            and self.volatility_index > 0
            and self.trend_strength > 0.3
        )


@dataclass(frozen=True)
class TradeResult:
    """
    Result of a completed trade.

    This captures all relevant information about a trade's lifecycle,
    from entry to exit, for performance analysis and learning.

    Attributes:
        trade_id: Unique trade identifier
        symbol: Trading pair symbol
        entry_time: When the trade was opened
        exit_time: When the trade was closed
        entry_price: Price at which position was opened
        exit_price: Price at which position was closed
        position_size: Size of the position
        direction: Long or short
        outcome: Trade outcome (WIN, LOSS, BREAKEVEN)
        pnl: Profit/loss amount
        pnl_percent: Profit/loss as percentage
        fees: Total trading fees paid
        slippage: Slippage incurred
        max_drawdown: Maximum drawdown during trade
        exit_reason: Why the trade was closed
        metadata: Additional trade data
    """

    trade_id: str
    symbol: str
    entry_time: datetime
    exit_time: datetime
    entry_price: float
    exit_price: float
    position_size: float
    direction: str  # "long" or "short"
    outcome: TradeOutcome
    pnl: float
    pnl_percent: float
    fees: float
    slippage: float
    max_drawdown: float
    exit_reason: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate the trade result after initialization."""
        if self.position_size <= 0:
            raise ValueError("position_size must be positive")
        if self.direction not in ("long", "short"):
            raise ValueError("direction must be 'long' or 'short'")

    def duration_seconds(self) -> float:
        """Calculate the duration of the trade in seconds."""
        return (self.exit_time - self.entry_time).total_seconds()

    def is_profitable(self) -> bool:
        """Check if the trade was profitable."""
        return self.pnl > 0

    def risk_adjusted_return(self) -> float:
        """Calculate risk-adjusted return (return per unit of risk)."""
        if self.max_drawdown == 0:
            return 0.0
        return self.pnl_percent / abs(self.max_drawdown)


@dataclass(frozen=True)
class ReviewReport:
    """
    Performance review report for trading analysis.

    This aggregates trade results and other metrics to produce
    a comprehensive review of trading performance over a period.

    Attributes:
        review_id: Unique review identifier
        start_time: Start of review period
        end_time: End of review period
        total_trades: Total number of trades
        winning_trades: Number of winning trades
        losing_trades: Number of losing trades
        breakeven_trades: Number of breakeven trades
        total_pnl: Total profit/loss
        average_pnl: Average profit/loss per trade
        win_rate: Percentage of winning trades
        profit_factor: Gross profit / gross loss
        sharpe_ratio: Risk-adjusted return measure
        max_drawdown: Maximum peak-to-trough decline
        average_trade_duration: Average time in trades
        largest_win: Largest single winning trade
        largest_loss: Largest single losing trade
        trade_ids: List of trade IDs included in review
    """

    review_id: str
    start_time: datetime
    end_time: datetime
    total_trades: int
    winning_trades: int
    losing_trades: int
    breakeven_trades: int
    total_pnl: float
    average_pnl: float
    win_rate: float
    profit_factor: float
    sharpe_ratio: float
    max_drawdown: float
    average_trade_duration: float
    largest_win: float
    largest_loss: float
    trade_ids: List[str]

    def __post_init__(self):
        """Validate the review report after initialization."""
        if self.total_trades < 0:
            raise ValueError("total_trades must be non-negative")
        if not 0 <= self.win_rate <= 1:
            raise ValueError("win_rate must be between 0 and 1")

    def calculate_expectancy(self) -> float:
        """Calculate the mathematical expectancy of the trading strategy."""
        if self.total_trades == 0:
            return 0.0

        avg_win = self.largest_win / max(self.winning_trades, 1)
        avg_loss = abs(self.largest_loss) / max(self.losing_trades, 1)

        return (self.win_rate * avg_win) - ((1 - self.win_rate) * avg_loss)


@dataclass(frozen=True)
class LearningReport:
    """
    Learning and improvement report for the AI trading system.

    This captures insights gained from trading experience,
    model performance improvements, and suggested adjustments.

    Attributes:
        report_id: Unique report identifier
        generated_at: When the report was generated
        period_start: Start of learning period
        period_end: End of learning period
        model_performance: Model accuracy metrics over time
        feature_importance: Ranking of feature contributions
        learned_patterns: Patterns identified as significant
        strategy_adjustments: Suggested strategy modifications
        risk_parameter_updates: Recommended risk parameter changes
        failure_analysis: Analysis of failed trades
        success_analysis: Analysis of successful trades
        recommendations: Actionable recommendations
        confidence_scores: Confidence in each recommendation
    """

    report_id: str
    generated_at: datetime
    period_start: datetime
    period_end: datetime
    model_performance: Dict[str, float] = field(default_factory=dict)
    feature_importance: Dict[str, float] = field(default_factory=dict)
    learned_patterns: List[str] = field(default_factory=list)
    strategy_adjustments: List[str] = field(default_factory=list)
    risk_parameter_updates: Dict[str, Any] = field(default_factory=dict)
    failure_analysis: Dict[str, Any] = field(default_factory=dict)
    success_analysis: Dict[str, Any] = field(default_factory=dict)
    recommendations: List[str] = field(default_factory=list)
    confidence_scores: Dict[str, float] = field(default_factory=dict)

    def __post_init__(self):
        """Validate the learning report after initialization."""
        for key, score in self.confidence_scores.items():
            if not 0 <= score <= 1:
                raise ValueError(f"confidence score for {key} must be between 0 and 1")

    def get_top_recommendations(self, n: int = 5) -> List[str]:
        """Get the top N recommendations sorted by confidence."""
        scored_recs = [
            (rec, self.confidence_scores.get(rec, 0.0))
            for rec in self.recommendations
        ]
        scored_recs.sort(key=lambda x: x[1], reverse=True)
        return [rec for rec, _ in scored_recs[:n]]

    def improvement_rate(self) -> float:
        """Calculate the rate of improvement in model performance."""
        if not self.model_performance:
            return 0.0

        # Assuming model_performance contains accuracy over time
        accuracies = list(self.model_performance.values())
        if len(accuracies) < 2:
            return 0.0

        return (accuracies[-1] - accuracies[0]) / len(accuracies)


# Export all classes and enums for convenient importing
__all__ = [
    # Enums
    "ActionType",  # Re-exported from provider.base for backward compatibility
    "SignalStrength",
    "MarketRegime",
    "TradeOutcome",
    # Data Classes
    "TradingSignal",
    "MarketContext",
    "TradeResult",
    "ReviewReport",
    "LearningReport",
]
